version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/server/server.dockerfile
    ports:
      - "5000:5000"
      - "5268:5268"
  web:
    build:
      context: .
      dockerfile: dockerfiles/ui/ui.dockerfile
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app/ui
